
max_results: 20

# file paths
json_readme_path: './docs/tts-arxiv-daily.json'

md_readme_path: 'README.md'

# keywords to search
keywords:
    "Flow Matching Related Papers":
        filters: ["flow matching"]


